### ISSUE TITLE
libgfortran and libtool need to rebuilt

### ISSUE THREAD

**Issue by allyunion** [allyunion/centos7-yum-repo-fbthrift#1]
--> Finished Dependency Resolution
Error: Package: libgfortran-4.8.5-28.el7_5.1.x86_64 (@updates)
           Requires: libquadmath = 4.8.5-28.el7_5.1
           Removing: libquadmath-4.8.5-28.el7_5.1.x86_64 (@updates)
               libquadmath = 4.8.2-16.el7_5
               libquadmath = 4.8.5-28.el7_5.1
           Updated By: libquadmath-4.9.4-1.el7.x86_64 (local-gcc)
               libquadmath = 4.9.4-1.el7
           Available: libquadmath-4.8.5-28.el7.x86_64 (base)
               libquadmath = 4.8.5-28.el7
               libquadmath = 4.8.2-16.el7
Error: Package: libtool-2.4.2-22.el7_3.x86_64 (@base)
           Requires: gcc = 4.8.5
           Removing: gcc-4.8.5-28.el7_5.1.x86_64 (@updates)
               gcc = 4.8.2-16.el7_5
               gcc = 4.8.5-28.el7_5.1
           Updated By: gcc-4.9.4-1.el7.x86_64 (local-gcc)
               gcc = 4.9.4-1.el7
           Available: gcc-4.8.5-28.el7.x86_64 (base)
               gcc = 4.8.5-28.el7
               gcc = 4.8.2-16.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by allyunion** [comment]
+ cd /builddir/build/BUILD
+ cd gcc-4.9.4-20150212
+ DOCDIR=/builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-devel-4.9.4
+ export DOCDIR
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-devel-4.9.4
+ cp -pr rpm.doc/changelogs/libstdc++-v3/ChangeLog-1998.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-1999.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2000.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2001.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2002.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2003.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2004.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2005.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2006.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2007.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2008.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2009.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2010.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2011.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2012.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog-2013.bz2 rpm.doc/changelogs/libstdc++-v3/ChangeLog.bz2 /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-devel-4.9.4
+ cp -pr libstdc++-v3/README /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-devel-4.9.4
+ exit 0
Provides: libstdc++-devel = 4.9.4-1.el7 libstdc++-devel(x86-64) = 4.9.4-1.el7
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Processing files: libstdc++-docs-4.9.4-1.el7.x86_64
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.ntIFoA
+ umask 022
+ cd /builddir/build/BUILD
+ cd gcc-4.9.4-20150212
+ DOCDIR=/builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-docs-4.9.4
+ export DOCDIR
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-docs-4.9.4
+ cp -pr rpm.doc/libstdc++-v3/html /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/libstdc++-docs-4.9.4
+ exit 0
Provides: libstdc++-docs = 4.9.4-1.el7 libstdc++-docs(x86-64) = 4.9.4-1.el7
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Processing files: gcc-gfortran-4.9.4-1.el7.x86_64
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.yu0GEU
+ umask 022
+ cd /builddir/build/BUILD
+ cd gcc-4.9.4-20150212
+ DOCDIR=/builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/gcc-gfortran-4.9.4
+ export DOCDIR
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/gcc-gfortran-4.9.4
+ cp -pr rpm.doc/gfortran/ChangeLog-2002.bz2 rpm.doc/gfortran/ChangeLog-2002.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2003.bz2 rpm.doc/gfortran/ChangeLog-2003.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2004.bz2 rpm.doc/gfortran/ChangeLog-2004.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2005.bz2 rpm.doc/gfortran/ChangeLog-2005.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2006.bz2 rpm.doc/gfortran/ChangeLog-2006.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2007.bz2 rpm.doc/gfortran/ChangeLog-2007.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2008.bz2 rpm.doc/gfortran/ChangeLog-2008.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2009.bz2 rpm.doc/gfortran/ChangeLog-2009.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2010.bz2 rpm.doc/gfortran/ChangeLog-2010.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2011.bz2 rpm.doc/gfortran/ChangeLog-2011.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2012.bz2 rpm.doc/gfortran/ChangeLog-2012.libgfortran.bz2 rpm.doc/gfortran/ChangeLog-2013.bz2 rpm.doc/gfortran/ChangeLog.bz2 rpm.doc/gfortran/ChangeLog.libgfortran.bz2 rpm.doc/gfortran/ChangeLog.ptr.bz2 /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/share/doc/gcc-gfortran-4.9.4
+ exit 0
Provides: gcc-gfortran = 4.9.4-1.el7 gcc-gfortran(x86-64) = 4.9.4-1.el7
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.11)(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.4)(64bit) libdl.so.2()(64bit) libdl.so.2(GLIBC_2.2.5)(64bit) libgmp.so.10()(64bit) libm.so.6()(64bit) libmpc.so.3()(64bit) libmpfr.so.4()(64bit) libz.so.1()(64bit) rtld(GNU_HASH)
Processing files: libgfortran-4.9.4-1.el7.x86_64
RPM build errors:
BUILDSTDERR: error: File not found by glob: /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/lib64/libgfortran.so.3*
BUILDSTDERR:     File not found by glob: /builddir/build/BUILDROOT/gcc-4.9.4-1.el7.x86_64/usr/lib64/libgfortran.so.3*
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 634, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
Error: Command failed:
 # /usr/bin/systemd-nspawn -q -M 31e278ce09974031a0356da1e916e0d3 -D /var/lib/mock/epel-7-x86_64/root --bind=/tmp/mock-resolv.sGnr_L:/etc/resolv.conf --setenv=LANG=en_US.UTF-8 --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOSTNAME=mock --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=HOME=/builddir --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PS1=<mock-chroot> \s-\v\$  -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/gcc.spec
